CREATE TABLE IF NOT EXISTS "Accidents" (
    "ID" BIGSERIAL PRIMARY KEY NOT NULL,
    "Severity" INT NOT NULL,
    "Start_Time" TIMESTAMP NOT NULL,
    "End_Time" TIMESTAMP NOT NULL,
    "Start_Lat" DOUBLE PRECISION NOT NULL,
    "Start_Lng" DOUBLE PRECISION NOT NULL,
    "End_Lat" DOUBLE PRECISION,
    "End_Lng" DOUBLE PRECISION,
    "Distance" DOUBLE PRECISION NOT NULL,
    "Number" DOUBLE PRECISION,
    "Street" VARCHAR(100),
    "Side" CHAR(1),
    "City" VARCHAR(30),  
    "County" VARCHAR(30),
    "State" CHAR(2),
    "Zipcode" VARCHAR(30),
    "Country" CHAR(2),
    "Timezone" VARCHAR(30),
    "Airport_Code" VARCHAR(10),
    "Weather_Timestamp" TIMESTAMP,
    "Temperature" DOUBLE PRECISION,
    "Wind_Chill" DOUBLE PRECISION,
    "Humidity" DOUBLE PRECISION,
    "Pressure" DOUBLE PRECISION,
    "Visibility" DOUBLE PRECISION,
    "Wind_Direction" VARCHAR(10),
    "Wind_Speed" DOUBLE PRECISION,
    "Precipitation" DOUBLE PRECISION,
    "Weather_Condition" VARCHAR(50),
    "Amenity" BOOLEAN NOT NULL,
    "Bump" BOOLEAN NOT NULL,
    "Crossing" BOOLEAN NOT NULL,
    "Give_Way" BOOLEAN NOT NULL,
    "Junction" BOOLEAN NOT NULL,
    "No_Exit" BOOLEAN NOT NULL,
    "Railway" BOOLEAN NOT NULL,
    "Roundabout" BOOLEAN NOT NULL,
    "Station" BOOLEAN NOT NULL,
    "Stop" BOOLEAN NOT NULL,
    "Traffic_Calming" BOOLEAN NOT NULL,
    "Traffic_Signal" BOOLEAN NOT NULL,
    "Turning_Loop" BOOLEAN NOT NULL,
    "Sunrise_Sunset" VARCHAR(10),
    "Civil_Twilight" VARCHAR(10),
    "Nautical_Twilight" VARCHAR(10),
    "Astronomical_Twilight" VARCHAR(10)
)